app:
    resource: "@AppBundle/Controller/"
    type:     annotation
student:
    resource: "@StudentBundle/Resources/config/routing.yml"
    prefix:   /
captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"