# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Ucict\Bundle\StudentBundle\Entity\User:
            algorithm: bcrypt
    providers:
        our_db_provider:
            entity:
                class: StudentBundle:User
                property: email			
    firewalls:
        main: 
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: 
                always_use_default_target_path: true
            pattern: ^/
            http_basic: ~
            provider: our_db_provider
            anonymous: true