student_homepage:
    path:     /
    defaults: { _controller: StudentBundle:Default:index }
register:
    path:     /register
    defaults: { _controller: StudentBundle:User:register }
login:
    path:     /login
    defaults: { _controller: StudentBundle:User:login }


