Ucict\Bundle\StudentBundle\Entity\Address:
    type: entity
    Address:
        oneToOne:
            addresses:
                targetEntity: Profile
                mappedBy: profile
    
        manyToOne:
            city:
                targetEntity: City
                inversedBy: addresses
                joinColumn:
                    name: contact_address_id
                    referencedColumnName: id

    table: Address
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        streetAddress: 
            type: string
            length: 512
        zip: 
            type: string
            length: 20
            nullable: true
        cityId:
            type: integer
            nullable: true