Ucict\Bundle\StudentBundle\Entity\City:
    type: entity
    manyToOne:
        region:
            targetEntity: Region
            inversedBy: cities
            joinColumn:
                name: region_id
                referencedColumnName: id

    oneToMany:
        addresses:
            targetEntity: Address
            mappedBy: city

    table: Nomenclature_CityEkatte
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name: 
            type: string
            length: 100
        regionId: 
            type: integer
            