Ucict\Bundle\StudentBundle\Entity\Profile:
    type: entity
    table: student_profile
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        birthDate: 
            type: date 
        phone:
            length: 32
            nullable: true
            type: string
        secondPhone:
            length: 32
            nullable: true
            type: string
        gsm:
            length: 32
            type: string
        secondGsm:
            length: 32
            type: string
            nullable: true
        graduateYear:
            type: integer
             
        genderId:
            type: integer

        contactAddressId: 
            type: integer
        
        # oneToOne:
        #   profile:
        #     targetEntity: Student
        #     mappedBy: student_profile       