Ucict\Bundle\StudentBundle\Entity\Student:
    type: entity
    table: student
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
    # oneToOne:
    #     profile:
    #             targetEntity: Profile
    #             inversedBy: student
    #             joinColumn:
    #                 name: profile_id
    #                 referencedColumnName: id
        user_id:
            type: integer
        profile_id:
            type: integer
        personal_number_type:
            type: integer
        first_name:
            type: string
            length: 255
        middle_name:
            type: string
            length: 255
        last_name:
            type: string
            length: 255
        other_name:
            type: string
            length: 255	
            nullable: true	
        personal_number:
            type: string
            length: 10
    # oneToOne:
    #   profile:
    #     targetEntity: Profile
    #     mappedBy: student       