Ucict\Bundle\StudentBundle\Entity\Student:
    type: entity
    table: student
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
    # oneToOne:
    #     profile:
    #             targetEntity: Profile
    #             inversedBy: student
    #             joinColumn:
    #                 name: profile_id
    #                 referencedColumnName: id
        userId:
            type: integer
        profileId:
            type: integer
        personalNumberType:
            type: integer
        firstName:
            type: string
            length: 255
        middleName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        otherName:
            type: string
            length: 255	
            nullable: true	
        personalNumber:
            type: string
            length: 10
    # oneToOne:
    #   profile:
    #     targetEntity: Profile
    #     mappedBy: student       