Ucict\Bundle\StudentBundle\Entity\Student:
    type: entity
    oneToOne:
    profile:
      targetEntity: Profile
      joinColumn:
        name: profile_id
        referencedColumnName: id
    table: student
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
   
        userId:
            type: integer
        
        personalNumberType:
            type: integer
        firstName:
            type: string
            length: 255
        middleName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        otherName:
            type: string
            length: 255	
            nullable: true	
        personalNumber:
            type: string
            length: 10
        profileId: 
            type: integer
    