Ucict\Bundle\StudentBundle\Entity\User:
    type: entity
    table: student_user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        email:
            type: string
            length: 255
        password:
            type: string
            length: 1000
        is_activated:
            type: integer